plugins {
    id 'base'
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}" apply false
}
tasks.named('build') { dependsOn ':fabric:build' }
tasks.named('assemble') { dependsOn ':fabric:assemble' }
tasks.named('check') { dependsOn ':fabric:check' }
tasks.register('test') {
    group = 'verification'
    dependsOn ':fabric:test'
}
