plugins { id 'net.neoforged.moddev' }
apply from: rootProject.file('gradle/loader.gradle')
neoForge {
    version = project.neoforge_version
    mods { librarian_insight { sourceSet sourceSets.main } }
    unitTest {
        enable()
        testedMod = mods.librarian_insight
    }
    runs {
        client {
            client()
            gameDirectory = file('run')
        }
    }
}
